# Generated by Django 6.0.3 on 2026-09-18 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128, unique=True)),
                ('model_version', models.CharField(default='1.0.0', max_length=32)),
                ('task', models.CharField(help_text='e.g. skin_lesion_screening, chest_xray_opacity, nlp_entity_extractor', max_length=128)),
                ('input_format', models.CharField(default='224x224 RGB Image', max_length=128)),
                ('output_format', models.CharField(default='Classification probabilities + uncertainty score', max_length=128)),
                ('accuracy_metrics', models.JSONField(default=dict, help_text='Evaluated accuracy, precision, recall, F1, AUROC')),
                ('training_dataset', models.CharField(default='ISIC Archive & NIH CXR-14 Clinical Subsets', max_length=255)),
                ('license', models.CharField(default='Apache 2.0 / Open Medical AI', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_offline_ready', models.BooleanField(default=True)),
                ('local_weights_path', models.CharField(blank=True, max_length=255)),
                ('last_updated', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('raw_input_text', models.TextField()),
                ('extracted_symptoms', models.JSONField(default=list)),
                ('negated_symptoms', models.JSONField(default=list)),
                ('duration_str', models.CharField(blank=True, max_length=128)),
                ('severity_level', models.CharField(default='Unknown', max_length=64)),
                ('risk_level', models.CharField(default='LOW', max_length=32)),
                ('matched_conditions', models.JSONField(default=list)),
                ('detected_warning_signs', models.JSONField(default=list)),
                ('decision_support_summary', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('system_version', models.CharField(default='2.4.0', max_length=32)),
                ('knowledge_version', models.IntegerField(default=18)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=128)),
                ('entity_id', models.CharField(blank=True, max_length=128)),
                ('details', models.TextField()),
                ('performed_by', models.CharField(default='System / Clinical Manager', max_length=128)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HealthcareFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('facility_type', models.CharField(choices=[('HOSPITAL', 'Multi-Speciality Hospital'), ('EMERGENCY_CENTER', '24/7 Emergency & Trauma Center'), ('CLINIC', 'Primary Health Clinic'), ('PHARMACY', 'Pharmacy / Chemist'), ('BLOOD_BANK', 'Blood Bank & Transfusion Unit'), ('DIAGNOSTIC_LAB', 'Diagnostic Laboratory & Imaging')], default='HOSPITAL', max_length=32)),
                ('latitude', models.FloatField(help_text='WGS-84 Latitude')),
                ('longitude', models.FloatField(help_text='WGS-84 Longitude')),
                ('address', models.TextField()),
                ('city', models.CharField(default='Metropolis', max_length=128)),
                ('phone', models.CharField(default='112 / 108', max_length=64)),
                ('emergency_phone', models.CharField(blank=True, help_text='Direct emergency line', max_length=64)),
                ('services', models.TextField(help_text='Comma-separated available clinical services')),
                ('is_24x7', models.BooleanField(default=True)),
                ('has_ambulance', models.BooleanField(default=True)),
                ('has_icu', models.BooleanField(default=True)),
                ('last_verified', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128)),
                ('image_quality_status', models.CharField(default='Adequate', max_length=64)),
                ('quality_score', models.FloatField(default=0.95)),
                ('inferred_category', models.CharField(max_length=128)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('uncertainty_level', models.CharField(default='Low', max_length=64)),
                ('findings_summary', models.TextField()),
                ('safety_disclaimer', models.TextField(default='Decision support screening prototype only. NOT a definitive medical diagnostic.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('organization', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('last_verified', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('mechanism', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='Medical', max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_version', models.IntegerField(unique=True)),
                ('previous_version', models.IntegerField(default=0)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('manifest_data', models.JSONField(default=dict)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-package_version'],
            },
        ),
        migrations.CreateModel(
            name='UserHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(default='local_user_default', max_length=64, unique=True)),
                ('encrypted_payload', models.TextField(blank=True, help_text='Client-side AES-GCM encrypted allergies, chronic conditions, and meds')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('criteria', models.JSONField(default=dict)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low / Informational'), ('CAUTION', 'Caution / Medical Attention Suggested'), ('URGENT', 'Urgent / Immediate Emergency Care Required')], default='URGENT', max_length=32)),
                ('warning_text', models.TextField(help_text='Direct patient advisory message shown with zero delay')),
                ('immediate_first_aid', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rule_version', models.CharField(default='1.0', max_length=32)),
                ('last_verified', models.DateField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swasthya_core.medicalsource')),
            ],
            options={
                'ordering': ['-risk_level', 'rule_id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='First Aid', max_length=128)),
                ('content', models.TextField()),
                ('step_by_step_guide', models.JSONField(blank=True, default=list)),
                ('warning_notes', models.TextField(blank=True)),
                ('last_verified', models.DateField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swasthya_core.medicalsource')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('generic_name', models.CharField(db_index=True, max_length=255)),
                ('brand_names', models.TextField(blank=True, help_text='Comma-separated popular brand names')),
                ('dosage_form', models.CharField(help_text='e.g. Tablet, Syrup, Inhaler, Topical Cream', max_length=128)),
                ('general_uses', models.TextField(help_text='General recognized indications')),
                ('warnings', models.TextField(help_text='Key precautions and black-box warnings')),
                ('contraindications', models.TextField(help_text='Conditions where this medicine must NOT be used')),
                ('common_side_effects', models.TextField(blank=True)),
                ('storage_information', models.TextField(default='Store below 25°C in a dry place away from direct sunlight and children.')),
                ('pregnancy_category', models.CharField(default='Consult Physician', max_length=32)),
                ('last_verified', models.DateField(default=django.utils.timezone.now)),
                ('review_status', models.CharField(default='Approved', max_length=50)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swasthya_core.medicalsource')),
                ('medicine_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='swasthya_core.medicineclass')),
            ],
            options={
                'ordering': ['generic_name'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(default='General Medicine', max_length=128)),
                ('overview', models.TextField()),
                ('recommended_evaluations', models.TextField(help_text='Recommended clinical evaluations for doctor consultation')),
                ('non_pharmacological_care', models.TextField(blank=True, help_text='Evidence-based home comfort and hydration support')),
                ('source_version', models.CharField(default='1.0', max_length=50)),
                ('last_verified', models.DateField(default=django.utils.timezone.now)),
                ('review_status', models.CharField(default='Approved', max_length=50)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swasthya_core.medicalsource')),
                ('risk_factors', models.ManyToManyField(blank=True, related_name='conditions', to='swasthya_core.riskfactor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('common_names', models.TextField(help_text='Comma-separated synonyms or colloquial terms')),
                ('body_system', models.CharField(default='General', max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_emergency_flag', models.BooleanField(default=False)),
                ('last_verified', models.DateField(default=django.utils.timezone.now)),
                ('review_status', models.CharField(default='Approved', max_length=50)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swasthya_core.medicalsource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConditionSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text='Relevance weight (0.1 to 1.0)')),
                ('is_pathognomonic', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('Very Common', 'Very Common (>80%)'), ('Common', 'Common (50-80%)'), ('Occasional', 'Occasional (20-50%)'), ('Rare', 'Rare (<20%)')], default='Common', max_length=64)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swasthya_core.condition')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swasthya_core.symptom')),
            ],
            options={
                'unique_together': {('condition', 'symptom')},
            },
        ),
        migrations.AddField(
            model_name='condition',
            name='symptoms',
            field=models.ManyToManyField(related_name='conditions', through='swasthya_core.ConditionSymptom', to='swasthya_core.symptom'),
        ),
        migrations.CreateModel(
            name='SyncPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('KNOWLEDGE', 'Medical Knowledge Base Delta'), ('MEDICINE', 'Medicine Repository Delta'), ('FACILITY', 'Healthcare Facility Directory Delta'), ('EMERGENCY_RULES', 'Emergency Rules Update'), ('AI_MODELS', 'Local AI Inference Weight Package')], max_length=64)),
                ('delta_payload', models.JSONField(default=dict)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('sha256_hash', models.CharField(max_length=64)),
                ('applied_successfully', models.BooleanField(default=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='swasthya_core.syncversion')),
            ],
        ),
        migrations.CreateModel(
            name='WarningSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity_level', models.CharField(choices=[('LOW', 'Low / Informational'), ('CAUTION', 'Caution / Medical Attention Suggested'), ('URGENT', 'Urgent / Immediate Emergency Care Required')], default='URGENT', max_length=20)),
                ('immediate_action', models.TextField(help_text='Standardized immediate first aid or emergency action guidance')),
                ('last_verified', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swasthya_core.medicalsource')),
            ],
            options={
                'ordering': ['-severity_level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='condition',
            name='warning_signs',
            field=models.ManyToManyField(blank=True, related_name='conditions', to='swasthya_core.warningsign'),
        ),
        migrations.CreateModel(
            name='MedicineInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('MINOR', 'Minor - Monitor'), ('MODERATE', 'Moderate - Caution advised'), ('MAJOR', 'Major - Avoid combination / Severe risk')], default='MODERATE', max_length=20)),
                ('description', models.TextField()),
                ('clinical_recommendation', models.TextField(blank=True)),
                ('medicine_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='swasthya_core.medicine')),
                ('medicine_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='swasthya_core.medicine')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swasthya_core.medicalsource')),
            ],
            options={
                'unique_together': {('medicine_a', 'medicine_b')},
            },
        ),
    ]
