# Generated by Django 6.0.3 on 2026-09-18 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthya_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomyStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique 3D structure identifier matching model object name', max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('alternative_names', models.CharField(blank=True, help_text='Common medical or vernacular synonyms', max_length=255)),
                ('system', models.CharField(help_text='Body system: Nervous, Cardiovascular, Respiratory, Digestive, Skeletal, Muscular, Endocrine, Urinary, Reproductive, Lymphatic', max_length=64)),
                ('sex', models.CharField(choices=[('both', 'Both'), ('male', 'Male Anatomy Only'), ('female', 'Female Anatomy Only')], default='both', max_length=20)),
                ('layer', models.CharField(default='organs', help_text='Anatomical layer: skin, skeleton, muscles, nervous, circulatory, respiratory, digestive, urinary, reproductive, endocrine', max_length=64)),
                ('model_object_name', models.CharField(blank=True, help_text='Matching 3D mesh name in Three.js scene', max_length=128)),
                ('location', models.CharField(blank=True, help_text='Anatomical region / landmark', max_length=128)),
                ('description', models.TextField(blank=True)),
                ('function', models.TextField(help_text='Concise physiological role of the structure')),
                ('common_concerns', models.TextField(blank=True, help_text='Frequently encountered non-emergency concerns')),
                ('general_care', models.TextField(blank=True, help_text='Evidence-based general self-care and monitoring guidance')),
                ('evaluation_guidance', models.TextField(blank=True, help_text='Clinical evaluation and specialist referral indications')),
                ('source_version', models.CharField(default='1.0', max_length=50)),
                ('last_verified', models.DateField(default=django.utils.timezone.now)),
                ('medicine_references', models.ManyToManyField(blank=True, related_name='anatomy_structures', to='swasthya_core.medicine')),
                ('related_conditions', models.ManyToManyField(blank=True, related_name='anatomy_structures', to='swasthya_core.condition')),
                ('related_symptoms', models.ManyToManyField(blank=True, related_name='anatomy_structures', to='swasthya_core.symptom')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swasthya_core.medicalsource')),
                ('warning_signs', models.ManyToManyField(blank=True, related_name='anatomy_structures', to='swasthya_core.warningsign')),
            ],
            options={
                'ordering': ['system', 'display_name'],
            },
        ),
    ]
